project:
  type: book
  output-dir: docs

book:
  title: "Learning SQL the Badass Way"
  author: "Edgar J. Treischl"
  reader-mode: true
  repo-url: https://github.com/edgar-treischl/SQLR
  chapters:
    - "index.qmd"
    - "01_intro.qmd"
    - "02_data_management.qmd"
    - "03_calculations.qmd"
    - "06_cheat.qmd"
    - "references.qmd"
    



bibliography: references.bib
cover-image: cover.jpg

format:
  html:
    theme: litera
  pdf:
    documentclass: scrreprt



